"""Negative controls prove the evaluator detects errors, not just own outputs."""
from copy import deepcopy
from datetime import date
from decimal import Decimal
import hashlib
from types import SimpleNamespace
import pytest

from finresearch_evals.scoring import amount, gold_values, anchor_gold, expected_calculations, audit_state


@pytest.fixture
def fixture():
    text='合并利润表\n单位:元\n2024年度 2023年度\n收入 130.00 100.00\n现金 10.00 20.00\n应收 50.00 30.00'
    page=SimpleNamespace(document_id='doc',pdf_page=1,normalized_text=text)
    doc=SimpleNamespace(ts_code='002371.SZ',reporting_period='2024',published_on=date(2025,4,25),sha256='a'*64)
    corpus=SimpleNamespace(documents={'doc':doc},pages={'page':page})
    metrics=[('revenue','收入','130','100'),('operating_cash_flow_net','现金','10','20'),('accounts_receivable','应收','50','30')]
    gold={'rows':[{'company_id':'002371.SZ','document_id':'doc','metric_id':m,'pdf_page':1,'header_page':1,
        'row_prefix':label,'row_line_count':1,'header_excerpts':['合并利润表','单位:元','2024年度 2023年度'],
        'values':{'2024':new,'2023':old}} for m,label,new,old in metrics]}
    evidence={'evidence_id':'ev','document_id':'doc','page_id':'page','company_id':'002371.SZ','pdf_page':1,'line_start':1,'line_end':6,'text':text,
        'evidence_sha256':hashlib.sha256(text.encode()).hexdigest()}
    observations=[]
    for m,_,new,old in metrics:
        for year,value in ((2024,new),(2023,old)):
            stock=m=='accounts_receivable'
            observations.append({'observation_id':f'{m}-{year}','company_id':'002371.SZ','metric_id':m,'fiscal_year':year,
                'value_status':'OBSERVED','standard_value':value,'standard_unit':'CNY_YUAN','currency':'CNY','statement_scope':'CONSOLIDATED',
                'document_id':'doc','document_sha256':'a'*64,'document_published_on':'2025-04-25','period_kind':'STOCK' if stock else 'FLOW',
                'observed_at':f'{year}-12-31' if stock else None,'period_start':None if stock else f'{year}-01-01','period_end':None if stock else f'{year}-12-31',
                'evidence_refs':[{'evidence_id':'ev'}]})
    # Literal independent expected values, not generated by the scoring oracle.
    calculations={'revenue_growth':('0.3','RATIO'),'operating_cash_flow_net_growth':('-0.5','RATIO'),
        'accounts_receivable_growth':(str(Decimal(2)/3),'RATIO'),'ocf_revenue_ratio_2023':('0.2','RATIO'),
        'ocf_revenue_ratio_2024':(str(Decimal(1)/13),'RATIO'),'ar_revenue_ratio_2023':('0.3','RATIO'),
        'ar_revenue_ratio_2024':(str(Decimal(5)/13),'RATIO'),'revenue_ocf_growth_gap_pp':('80','PERCENTAGE_POINT')}
    state={'context':{'company_ids':['002371.SZ'],'fiscal_years':[2023,2024],'as_of_date':'2025-04-30'},
        'observations':observations,'evidence':[evidence],
        'calculations':{'002371.SZ':{k:{'status':'VALID','value':v,'output_unit':u} for k,(v,u) in calculations.items()}},
        'claims':[{'claim_id':'q1','company_id':'002371.SZ','kind':'DISCLOSED','text':'公司披露：“收入 130.00 100.00”','evidence_ids':['ev']}],
        'execution_status':'COMPLETED'}
    return gold,corpus,state


def test_literal_gold_anchors_and_independent_formulas(fixture):
    gold,corpus,state=fixture
    assert len(anchor_gold(gold,corpus))==3
    result=audit_state(state,gold,corpus)
    assert result['observations']['correct']==6
    assert result['calculations']['correct']==8
    assert not result['issues']
    assert result['semantic_review']['status']=='PENDING_INDEPENDENT_HUMAN_REVIEW'


@pytest.mark.parametrize('field,value',[('standard_value','999'),('fiscal_year',2022),('standard_unit','CNY_WANYUAN'),
    ('document_published_on','2024-01-01'),('document_sha256','b'*64),('statement_scope','PARENT'),('currency','USD'),
    ('period_start','2024-02-01'),('document_id','other')])
def test_bad_fact_metadata_not_accepted(fixture,field,value):
    gold,corpus,state=fixture
    state['observations'][0][field]=value
    result=audit_state(state,gold,corpus)
    assert result['observations']['correct']==5
    assert result['issues']
    assert result['observations']['expected']==6


def test_missing_fact_keeps_denominator(fixture):
    gold,corpus,state=fixture
    state['observations'].pop()
    r=audit_state(state,gold,corpus)
    assert r['observations']['correct']==5 and r['observations']['expected']==6 and r['observations']['missing']==1


@pytest.mark.parametrize('mutation',['wrong_value','wrong_unit','wrong_status','nan','extra_calculation'])
def test_calculation_mutation_detected(fixture,mutation):
    gold,corpus,state=fixture
    c=state['calculations']['002371.SZ']['revenue_growth']
    if mutation=='wrong_value':c['value']='30'
    if mutation=='wrong_unit':c['output_unit']='PERCENTAGE_POINT'
    if mutation=='wrong_status':c['status']='NEGATIVE_BASE'
    if mutation=='nan':c['value']='NaN'
    if mutation=='extra_calculation':state['calculations']['002371.SZ']['invented']={'value':'100'}
    r=audit_state(state,gold,corpus)
    assert r['calculations']['errors'] or r['issues']
    assert r['calculations']['expected']==8


def test_negative_base_is_not_a_growth_percentage(fixture):
    gold,_,_=fixture
    gold['rows'][1]['values']['2023']='-20'
    oracle=expected_calculations(gold_values(gold))['002371.SZ']
    assert oracle['operating_cash_flow_net_growth']['status']=='NEGATIVE_BASE'
    assert oracle['operating_cash_flow_net_growth']['value'] is None
    assert oracle['ocf_revenue_ratio_2023']['value']==Decimal('-0.2')
    assert oracle['revenue_ocf_growth_gap_pp']['status']=='INCOMPARABLE'


def test_zero_denominator(fixture):
    gold,_,_=fixture
    gold['rows'][0]['values']['2023']='0'
    oracle=expected_calculations(gold_values(gold))['002371.SZ']
    assert oracle['revenue_growth']['status']=='ZERO_DENOMINATOR'
    assert oracle['ar_revenue_ratio_2023']['value'] is None


@pytest.mark.parametrize('mutation',['quote','hash','lines','future_cutoff','claim_company','dependency','causal_gap'])
def test_provenance_or_false_gap_closure_detected(fixture,mutation):
    gold,corpus,state=fixture
    if mutation=='quote':state['claims'][0]['text']='公司披露：“增长已独立证实”'
    if mutation=='hash':state['evidence'][0]['evidence_sha256']='b'*64
    if mutation=='lines':state['evidence'][0]['line_end']=999
    if mutation=='future_cutoff':state['context']['as_of_date']='2025-01-01'
    if mutation=='claim_company':state['claims'][0]['company_id']='688082.SH'
    if mutation=='dependency':state['claims'][0]['calculation_ids']=['unknown']
    if mutation=='causal_gap':state['supplement']={'gaps':[{'gap_type':'INDEPENDENT_CONFIRMATION','status':'RESOLVED','gap_id':'bad'}]}
    assert audit_state(state,gold,corpus)['issues']


def test_gold_order_or_duplicate_cannot_self_certify(fixture):
    gold,corpus,_=fixture
    gold['rows'][0]['values']={'2023':'130','2024':'100'}
    with pytest.raises(ValueError):anchor_gold(gold,corpus)
    gold['rows'].append(deepcopy(gold['rows'][0]))
    with pytest.raises(ValueError):gold_values(gold)


@pytest.mark.parametrize('value',[float('nan'),0.3,True,'Infinity'])
def test_exact_amount_rejects_float_bool_nonfinite(value):
    with pytest.raises(ValueError):amount(value)
